@startuml
'https://plantuml.com/class-diagram



class Larik{

+{static} cetak(array : int[]) : void
+{static} sequentialSearch(array : int[])
+{static} binarySearch(array : int[])) : void
+{static} interpolationSearch((array : int[]) : void
+{static} bubbleSort(array : int[], isAscending : boolean) : void
+{static} selectionSort(array : int[], isAscending :boolean) :void
+{static} insertionSort(array : int [], isAscending : boolean) : void
+{static} quickSort(array : int[]) : void
-{static} quickSort(array : int[], lowIndex : int, highIndex : int) : void
+{static} swap(array : int[], firstIndex : int, secondIndex : int) :void
+{static} mergeSort(array : int[]) : void
-{static} mergeSort(array : int[], auxArray : int[],  lowIndex : int, highIndex :int) : void
-{static} mergeArrays(array : int[], auxArray : int[], lowIndex : int, mid : int, highIndex : int) : void



}

@enduml